name: Bug Report
description: Report unintended behavior, issues, or problems
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have **checked both [open and closed issues](https://github.com/encythe/bg-issuetracker/issues?q=is:issue)** to ensure this bug hasn't already been reported.
        - label: My server is on the **latest version**.
        - label: I am certain this is a **bug report**, not a suggestion.
  - type: dropdown
    attributes:
      label: Severity
      options:
        - Critical
        - Major
        - Moderate
        - Minor
  - type: dropdown
    attributes:
      label: Game
      options:
        - Difficulty Upgrade Tree
        - Not JJT Upgrade Tree
        - Other; specify
    validations:
      required: true
  - type: input
    attributes:
      label: Specify other [if selected]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
  - type: textarea
    attributes:
      label: Current vs Expected behavior
    validations:
      required: true
  